# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  FlatBread_config = debug

else ifeq ($(config),release)
  FlatBread_config = release

else ifeq ($(config),dist)
  FlatBread_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := FlatBread

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

FlatBread:
ifneq (,$(FlatBread_config))
	@echo "==== Building FlatBread ($(FlatBread_config)) ===="
	@${MAKE} --no-print-directory -C . -f FlatBread.make config=$(FlatBread_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f FlatBread.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   FlatBread"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"